services:
  frontend: # Definition of the frontend service
    build: 
      context: . # Builds the image from the current directory
      dockerfile: Dockerfile # Uses the Dockerfile from the current directory to build the image
    container_name: frontend # Sets the container name to "frontend"
    ports:
      - "5173:5173" # Maps port 5173 in the container to port 5173 on the host
    environment:
      - VITE_APP_BACKEND_ADDRESS=http://backend:3000/backend # Environment variable pointing to the backend address
    networks:
      - network # The service is connected to the network named "network"

  backend: # Definition of the backend service
    working_dir: /app # Sets the working directory in the container to "/app"
    build:
      context: ./backend # Builds the Docker image from the "./backend" directory
    container_name: backend # Sets the container name to "backend"
    command: node server.js # Runs the `node server.js` command when the container starts
    ports:
      - "3000:3000" # Maps port 3000 in the container to port 3000 on the host
    networks:
      - network # The service is connected to the "network"

networks:
  network: # Definition of the network that allows services to communicate
